docs: Change docs to `sphinx` and use rST docstring format
an-dyy/Lefi pull request #15
Opened 2021-11-14 02:30 UTC by an-dyy

This PR switches docs to `sphinx` from `mkdocs` and change docstring format to `reStructedText`

2021-11-14 03:39 UTC, anand2312 requested changes
I think you've missed the CI file that auto-deploys docs (but I'm not sure I'm doing this on mobile 😔)

2021-11-14 03:39 UTC, anand2312 commented on docs/rtd_requirements.txt
>  mkdocs-material >= "7.3.2"
Not needed anymore

2021-11-14 03:51 UTC, an-dyy commented on docs/rtd_requirements.txt
>  mkdocs-material >= "7.3.2"
Thanks, fixed

2021-11-16 05:27 UTC, an-dyy commented
Merging right now, instead of finishing then merging to save some time later

2021-11-16 05:27 UTC, merged