Slash command converters
an-dyy/Lefi pull request #16
Opened 2021-12-09 23:46 UTC by Shom770

Implements slash command converters

*Note: If you see a lot of `#type: ignore` comments in `./objects/interactions/converters.py`, it's because I had to wrap the typehints in a string to prevent a circular import error when importing the actual objects. This led to a lot of mypy errors saying 'name is not defined', hence I add to add those 'type: ignore' comments.

2021-12-10 00:04 UTC, an-dyy commented on examples/example_bot.py
> +@commands.check(lambda ctx: ctx.author.id in (270700034985558017, 584817706646110333))
Left this in

2021-12-10 00:04 UTC, an-dyy commented on lefi/exts/commands/bot.py
> +        print(type(error), error)
Left this in

2021-12-10 00:07 UTC, Shom770 commented
Fixed

2021-12-10 00:08 UTC, an-dyy commented on lefi/objects/interactions/converters.py
> +        data = await interaction.client.http.get_user(user_id)
`lefi.Client.fetch_user` now exists, you don't need to call directly to the HTTPClient

2021-12-10 00:09 UTC, an-dyy commented on lefi/objects/interactions/converters.py
> +        return guild.get_channel(channel_id)
Only would work if the channel is cached, you should be calling `fetch_channel` here

2021-12-10 00:11 UTC, an-dyy commented on lefi/objects/interactions/converters.py
> +        return guild.get_role(role_id)
Would only work if the role is cached, although this is in a grey spot. You would need to use `fetch_roles` as discord doesn't have way currently as of now to fetch a specific role.

2021-12-10 00:13 UTC, an-dyy commented on lefi/objects/interactions/parser.py
> +    """
These aren't the correct docstring format. The library has been changed to rST styled docstrings, although some of the files are still in the outdated format

2021-12-10 00:13 UTC, an-dyy commented on lefi/objects/interactions/parser.py
> +        """
Outdated docstring format

2021-12-10 00:14 UTC, an-dyy commented on lefi/objects/interactions/parser.py
> +    async def create_arguments(self, interaction: Interaction, data: List[Dict]) -> List:
The return statement should have the relevant classes, as there can only be certain types for slash commands

2021-12-10 00:17 UTC, an-dyy commented on lefi/objects/interactions/parser.py
> +        data: :class:`list`
This can be changed to List[Union[:class:`A`, :class:`B`]], after typehinting the return

2021-12-10 00:28 UTC, an-dyy commented on lefi/objects/interactions/parser.py
> +        ----------
Extra underscores

2021-12-10 00:28 UTC, an-dyy commented on lefi/objects/interactions/parser.py
> +        ----------
Extra underscores

2021-12-10 00:31 UTC, an-dyy commented on .gitignore
> -test.py
Why was this removed from `.gitignore`?

2021-12-12 16:40 UTC, an-dyy commented on lefi/objects/interactions/converters.py
> +    """
All of these docstrings are indented another level whilst the rest of the library doesn't do that. It should be 
```py
"""Stuff
More stuff if needed
"""
```

2021-12-12 16:40 UTC, an-dyy commented on lefi/objects/interactions/converters.py
> +        """
Read the above comment

2021-12-12 16:47 UTC, an-dyy commented on lefi/objects/interactions/converters.py
> +        Converts a string to an integer.
Read the above comment

2021-12-12 16:48 UTC, an-dyy commented on lefi/objects/interactions/converters.py
> +        Converts the ID passed in into a User.
Read the above comment

2021-12-12 16:48 UTC, an-dyy commented on lefi/objects/interactions/converters.py
> +        Converts a string to a boolean.
Read the above comment

2021-12-12 16:49 UTC, an-dyy commented on lefi/objects/interactions/parser.py
> +    ---------
Missing an underscore

2021-12-12 16:50 UTC, an-dyy commented on lefi/objects/interactions/parser.py
> +        The [Command](./command.md) object.
Wrong format. Read the other rST docstrings to reference

2021-12-12 16:52 UTC, an-dyy commented on lefi/objects/interactions/parser.py
> +        The [Command](./command.md) object.
Wrong format. Read the other rST docstrings as a reference please

2021-12-12 16:52 UTC, an-dyy commented on lefi/objects/interactions/parser.py
> +        ---------
Missing underscore

2021-12-12 16:52 UTC, an-dyy commented on lefi/objects/interactions/parser.py
> +        ---------
Missing underscore

2021-12-12 16:52 UTC, an-dyy commented on lefi/objects/interactions/parser.py
> +        ---------
To many underscores

2021-12-12 16:53 UTC, an-dyy commented on lefi/objects/interactions/parser.py
> +        :class:`list[Union[str, int, bool, Member, User, Channel, Role]]`
This should be List[Union[:class:`A`, :class:`B`]]. Again, please read the other rST docstrings as a reference

2021-12-12 16:54 UTC, an-dyy commented on lefi/objects/interactions/parser.py
> +        ---------
Extra underscores

2021-12-12 16:54 UTC, an-dyy commented on lefi/objects/interactions/parser.py
> +        :class:`list[tuple[str, CommandOptionTypes]]`
This should be List[Tuple[:class:`str`, :class:`.CommandOptionTypes`]]

2021-12-12 16:55 UTC, an-dyy commented on lefi/objects/interactions/parser.py
> +        :class:`tuple[str, CommandOptionType]`
Read the above comment.

2021-12-12 16:55 UTC, an-dyy commented on lefi/objects/interactions/parser.py
> +        ---------
Missing underscores

2021-12-12 16:55 UTC, an-dyy commented on lefi/objects/interactions/parser.py
> +        ---------
Extra underscores

2021-12-12 16:56 UTC, an-dyy requested changes
These need to be fixed. You also need to delete the `.env` file you commited.

2021-12-14 23:40 UTC, merged